name: Team Tile Set
context: 
  members: 
    - image: '/media/images/team/marc.png'
      name: Marc Sen
      role: Inhaber
      email: marc.sen@reiheacht.ch
    - image: '/media/images/team/andrea.png'
      name: Marc Sen
      role: Inhaber
      email: marc.sen@reiheacht.ch
    - image: '/media/images/team/julia.png'
      name: Marc Sen
      role: Inhaber
      email: marc.sen@reiheacht.ch
   