fieldLayouts:
  78a3e7d5-07ec-41dc-9931-4ba845fe5f12:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: edda66b7-c42a-4454-9755-9c28dda0d07a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: intro
hasTitleField: false
name: Intro
section: 7944098d-e401-4ce5-8978-77973ce69099 # Blog
sortOrder: 2
titleFormat: Intro
titleTranslationKeyFormat: null
titleTranslationMethod: site
