name: Reference Slider
context: 
  items: 
    - quote: 'reiheacht hat es geschafft meine Ideen 1:1 umzusetzen. Ich bin sehr glücklich über das Resultat! Unser Maskottchen «Sporty» gibt es nun als Icon und als sportliche Illustrationen. Tolle Arbeit – vielen Dank!'
      author: 'Michèle Bucher'
      role: 'Leiterin Werbung'
      logo: '/media/graphics/logos/sportcard.svg'
    - quote: 'Lesen ist out. Wer sich informieren will, schaut heute ein Video. Das Angebot von reiheacht eignet sich perfekt, um Informationen zielgruppengerecht zu visualisieren.'
      author: 'Sandra Helfenstein'
      role: 'Co-Leiterin Kommunikation'
      logo: '/media/graphics/logos/sbv.svg'
    - quote: 'Dank der persönlichen Beratung haben wir für unser Crowdfunding Projekt schnell die passende Lösung gefunden. Emotionale Bilder die bewegen haben zum Erfolg für die Realisierung beigetragen. Herzlichen Dank.'
      author: 'Lukas Bregenzer'
      role: 'Inhaber'
      logo: '/media/graphics/logos/swiss-local-travel.svg'
    - quote: 'reiheacht hat uns vom Storyboard über das Drehen bis hin zur fertigen Produktion sehr kompetent unterstützt. Dank seiner freundlichen, humorvollen und professionellen Art und Weise war die Zusammenarbeit mit Marc jederzeit sehr angenehm.'
      author: 'Natasa Kovacevic'
      role: 'Leiterin Marketing'
      logo: '/media/graphics/logos/it-point.svg'
    - quote: 'Herzlichen Dank an das reiheacht Team, welches uns von A - Z professionell unterstützt und beraten hat. Wir freuen uns auf eine weitere Zusammenarbeit.'
      author: 'Thomas Rüttimann'
      role: 'Materialchef'
      logo: '/media/graphics/logos/gcz.svg'
    - quote: 'Unkomplizierte und sehr speditive Zusammenarbeit. Kann ich nur weiterempfehlen. Falls ich wieder ein Video brauche, komme ich definitiv wieder auf euch zu.'
      author: 'Jessica Glaus'
      role: 'Inhaberin'
      logo: '/media/graphics/logos/hairbreak.svg'
    - quote: 'reiheacht hat die Creatives für unsere Adventskampagne 2021 schnell und unkompliziert gestaltet. Unsere Illustrationen aus früheren Projekten haben sie geschickt weiterentwickelt, so dass wir viele Variationen umsetzen konnten. '
      author: 'Dorothea Portmann'
      role: 'Fachspezialistin Kommunikation'
      logo: '/media/graphics/logos/hotellerie-suisse.svg'
    - quote: 'Marc hat uns von der Konzeption bis zum fertigen Werbevideo professionell und kreativ unterstützt. Wir sind begeistert vom Ergebnis und würden reiheacht wieder wählen. '
      author: 'Daniel Gares'
      role: 'Leiter Verkauf & Marketing'
      logo: '/media/graphics/logos/altuna.svg'