name: Blog Detail
preview: "@bright"
context: 
  title: Die Welt der Farben
  image: '/media/images/service-tiles/motion-design.png'
  paragraph: In diesem Blogbeitrag erkunden wir die Welt der Farben, weit über den Horizont von Schwarz und Weiss hinaus. Hier gibt es Wissen, Tipps und Tricks, damit dein Markenauftritt auch farblich eine super Gattung macht.
