field: 1dd04d2d-76aa-4f79-98e2-15667bb18762 # Service Detail Content
fieldLayouts:
  2e3a04d6-5750-442a-8a8e-5c8482049a54:
    tabs:
      -
        elements:
          -
            fieldUid: f9a4f208-386c-4c54-b227-23fed38c8443 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 68b8c0a1-aa06-42d4-937d-04cd7138344c # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8cbcb54e-f568-4000-ae26-3687382f0088 # Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8cbcb54e-f568-4000-ae26-3687382f0088: # Tag
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: tag
    instructions: ''
    name: Tag
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Heading H2'
            -
              - value
              - h2
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Heading H3'
            -
              - value
              - h3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Heading H4'
            -
              - value
              - h4
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  68b8c0a1-aa06-42d4-937d-04cd7138344c: # Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: color
    instructions: ''
    name: Color
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - white
            -
              - value
              - white
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - black
            -
              - value
              - black
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - blue
            -
              - value
              - blue
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - orange
            -
              - value
              - orange
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f9a4f208-386c-4c54-b227-23fed38c8443: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heading
name: Heading
sortOrder: 1
