field: 8f3701ae-b853-4cdc-8277-b196dbf3efd0 # Blog Detail Content
fieldLayouts:
  05810822-62b8-4e6e-a5a1-b91b73546f16:
    tabs:
      -
        elements:
          -
            fieldUid: 0ef451cf-adc2-4b03-88de-819fe2d1fe69 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 760a3780-08ee-4b06-bc26-fcaf8244b8c9 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 16f5cce3-659f-41b6-9b77-72bf4d772941 # Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0ef451cf-adc2-4b03-88de-819fe2d1fe69: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  16f5cce3-659f-41b6-9b77-72bf4d772941: # Tag
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: tag
    instructions: ''
    name: Tag
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Heading H2'
            -
              - value
              - h2
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Heading H3'
            -
              - value
              - h3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Heading H4'
            -
              - value
              - h4
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  760a3780-08ee-4b06-bc26-fcaf8244b8c9: # Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: color
    instructions: ''
    name: Color
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - white
            -
              - value
              - white
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - black
            -
              - value
              - black
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - orange
            -
              - value
              - orange
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - blue
            -
              - value
              - blue
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: heading
name: Heading
sortOrder: 5
