field: 1dd04d2d-76aa-4f79-98e2-15667bb18762 # Service Detail Content
fieldLayouts:
  85581eed-397b-4edf-9cc8-487a762ccd94:
    tabs:
      -
        elements:
          -
            fieldUid: cd8ceb3b-40fe-4b1e-96e4-9ecb7ea60f4b # Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  cd8ceb3b-40fe-4b1e-96e4-9ecb7ea60f4b: # Source
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: source
    instructions: ''
    name: Source
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:06941c4d-93a8-4248-ae7a-66b38dcde9ff' # Service Assets
      defaultUploadLocationSubpath: ''
      limit: '2'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:bcb328af-f26b-4687-80c2-af0d1ae93a5b' # Logos
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:06941c4d-93a8-4248-ae7a-66b38dcde9ff' # Service Assets
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 3
