field: 8f3701ae-b853-4cdc-8277-b196dbf3efd0 # Blog Detail Content
fieldLayouts:
  d2f44201-4ca2-4ea0-b99b-456e6ab3e7a6:
    tabs:
      -
        elements:
          -
            fieldUid: ebc4bf8d-f213-4101-ac40-853208f5b06f # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d6457f11-2a05-46e9-97d9-3f319037fb35 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  d6457f11-2a05-46e9-97d9-3f319037fb35: # Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: color
    instructions: ''
    name: Color
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - white
            -
              - value
              - white
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - black
            -
              - value
              - black
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  ebc4bf8d-f213-4101-ac40-853208f5b06f: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: paragraph
name: Paragraph
sortOrder: 3
