field: 8f3701ae-b853-4cdc-8277-b196dbf3efd0 # Blog Detail Content
fieldLayouts:
  7f725a4f-bfb6-47ad-93e5-87285adf63a6:
    tabs:
      -
        elements:
          -
            fieldUid: f57166dc-8c65-4439-92c5-dadba8317127 # Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  f57166dc-8c65-4439-92c5-dadba8317127: # Source
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: source
    instructions: ''
    name: Source
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: video
name: Video
sortOrder: 2
