columnSuffix: jbowkbca
contentColumnType: text
fieldGroup: bd95c630-a4c4-4814-93b3-efc79b489aea # Hero
handle: heroTeaser
instructions: ''
name: 'Hero Teaser'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
