columnSuffix: sbgkkuag
contentColumnType: string(7)
fieldGroup: c656f1bc-b3e7-4e6b-bea8-da1f3254e94e # Project
handle: projectTileColor
instructions: ''
name: 'Project Tile Color'
searchable: false
settings:
  defaultColor: '#0374b6'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
