columnSuffix: egqygexi
contentColumnType: text
fieldGroup: c656f1bc-b3e7-4e6b-bea8-da1f3254e94e # Project
handle: projectInfoboxHeading
instructions: ''
name: 'Project Infobox Heading'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
