columnSuffix: null
contentColumnType: string
fieldGroup: c656f1bc-b3e7-4e6b-bea8-da1f3254e94e # Project
handle: projectDetailContent
instructions: ''
name: 'Project Detail Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_projectdetailcontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
