columnSuffix: spjunywl
contentColumnType: text
fieldGroup: 09aa1ffb-6601-431f-9955-4b1b0d42ce23 # Reference
handle: referenceRole
instructions: ''
name: 'Reference Role'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
