columnSuffix: null
contentColumnType: string
fieldGroup: ba93179b-304c-4eec-94e9-53eae4670e3f # Service
handle: serviceDetailContent
instructions: ''
name: 'Service Detail Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_servicedetailcontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
