columnSuffix: rfhmumrg
contentColumnType: text
fieldGroup: f4727773-dd07-4b66-a356-100798d9a6dc # Team
handle: teamTileRole
instructions: ''
name: 'Team Tile Role'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
