columnSuffix: aieahwti
contentColumnType: string(255)
fieldGroup: 4d0c44d3-2a40-4862-bbb6-3e65820d886b # Social Media Links
handle: youtube
instructions: ''
name: YouTube
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
