defaultPlacement: end
enableVersioning: true
handle: agbs
name: agbs
propagationMethod: all
siteSettings:
  639cd615-fa76-49be-a252-a4af968023e9: # Reiheacht
    enabledByDefault: true
    hasUrls: true
    template: pages/agbs.twig
    uriFormat: agbs
type: single
