defaultPlacement: end
enableVersioning: true
handle: blogOverview
name: 'Blog Overview'
propagationMethod: all
siteSettings:
  639cd615-fa76-49be-a252-a4af968023e9: # Reiheacht
    enabledByDefault: true
    hasUrls: true
    template: pages/blog-overview.twig
    uriFormat: blog-overview
type: single
