defaultPlacement: end
enableVersioning: true
handle: blogPosts
name: 'Blog Posts'
propagationMethod: all
siteSettings:
  639cd615-fa76-49be-a252-a4af968023e9: # Reiheacht
    enabledByDefault: true
    hasUrls: true
    template: pages/blog-posts.twig
    uriFormat: '{parent.uri}/{slug}'
type: channel
