defaultPlacement: end
enableVersioning: true
handle: references
name: References
propagationMethod: all
siteSettings:
  639cd615-fa76-49be-a252-a4af968023e9: # Reiheacht
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
