name: Home
context: 
  closeTriangle: true
  members:
    - image: '/media/images/team/marc.png'
      name: Marc Sen
      role: Inhaber
      email: marc.sen@reiheacht.ch
    - image: '/media/images/team/andrea.png'
      name: Marc Sen
      role: Inhaber
      email: marc.sen@reiheacht.ch
    - image: '/media/images/team/julia.png'
      name: Marc Sen
      role: Inhaber
      email: marc.sen@reiheacht.ch
  services: 
    - image: 'http://vlzrpwyey.cyon.link/uploads/service-tiles/web.webp'
      title: Videokonzeption
      href: '#'
    - image: 'http://vlzrpwyey.cyon.link/uploads/service-tiles/storytelling.webp'
      title: Storytelling
      href: '#'
    - image: 'http://vlzrpwyey.cyon.link/uploads/service-tiles/illustration.webp'
      title: Motion Design
      href: '#'
    - image: 'http://vlzrpwyey.cyon.link/uploads/service-tiles/film.webp'
      title: Erklärvideo
      href: '#'
    - image: 'http://vlzrpwyey.cyon.link/uploads/service-tiles/web.webp'
      title: Realfilm
      href: '#'
    - image: 'http://vlzrpwyey.cyon.link/uploads/service-tiles/sound.webp'
      title: Sound-Design
      href: '#'
  projects: 
    - title: reiheacht
      subtitle: Showreel
      image: 'http://vlzrpwyey.cyon.link/uploads/project-tiles/reiheacht.webp'
      color: '#0374B6'
      href: 
    - title: Sportcard
      subtitle: Sporty als Chatbot
      image: 'http://vlzrpwyey.cyon.link/uploads/project-tiles/sporty.webp'
      color: '#0071A6'
      href: 
    - title: ITpoint
      subtitle: Imagefilm 2021
      image: 'http://vlzrpwyey.cyon.link/uploads/project-tiles/it-point.webp'
      color: '#004A8F'
      href: 
    - title: Holliger Imballegno 
      subtitle: Altuna Box
      image: 'http://vlzrpwyey.cyon.link/uploads/project-tiles/altuna-box.webp'
      color: '#0072BC'
      href: 
    - title: Schweizer Bauernverband
      subtitle: Extreme Agrarinitiative
      image: 'http://vlzrpwyey.cyon.link/uploads/project-tiles/extreme-agrarinitiative.webp'
      color: '#9EA600'
      href: 
    - title: HotellerieSuisse
      subtitle: Adventskampagne 2021
      image: 'http://vlzrpwyey.cyon.link/uploads/project-tiles/adventsaktion.webp'
      color: '#DA291C'
      href: 
    - title: Schweizer Bauernverband
      subtitle: Trinkwasserinitiative
      image: 'http://vlzrpwyey.cyon.link/uploads/project-tiles/trinkwasserinitiative.webp'
      color: '#9EA600'
      href: 
    - title: Schweizer Bauernverband
      subtitle: diverse Erklärfilme
      image: 'http://vlzrpwyey.cyon.link/uploads/project-tiles/sbv-div.webp'
      color: '#9EA600'
      href: 
    - title: Gallo Suisse
      subtitle: Extreme Agrarinitiative
      image: 'http://vlzrpwyey.cyon.link/uploads/project-tiles/agrarinitiative.webp'
      color: '#C70103'
      href: 
  links:
    - label: Home
      href: '/#home'
      section: 'home'
    - label: Leistungen 
      href: '/#leistungen'
      section: 'leistungen'
    - label: Projekte
      href: '/#projekte'
      section: 'projekte'
    - label: Team
      href: '/#team'
      section: 'team'
    - label: Kontakt
      href: '/#kontakt'
      section: 'kontakt'
    - label: Blog
      href: '/blog'
      section: 'blog'
  address:
    - text: reiheacht Marketing GmbH
    - text: Spillgässli 12
    - text: 6205 Eich
    - text: hallo@reiheacht.ch
      href: mailto:hallo@reiheacht.ch
    - text: +41 41 552 06 00
      href: tel:+41415520600
  socialMedia:
    - icon: youtube
      href: '#'   
    - icon: vimeo
      href: '#'   
    - icon: linkedin
      href: '#'      
    - icon: twitter
      href: '#'
  anchors:
    - text: Impressum
      href: ''
    - text: Datenschutz
      href: ''
    - text: AGB
      href: ''
  items: 
    - quote: 'reiheacht hat es geschafft meine Ideen 1:1 umzusetzen. Ich bin sehr glücklich über das Resultat! Unser Maskottchen «Sporty» gibt es nun als Icon und als sportliche Illustrationen. Tolle Arbeit – vielen Dank!'
      author: 'Michèle Bucher'
      role: 'Leiterin Werbung'
      logo: '/media/graphics/logos/sportcard.svg'
    - quote: 'Lesen ist out. Wer sich informieren will, schaut heute ein Video. Das Angebot von reiheacht eignet sich perfekt, um Informationen zielgruppengerecht zu visualisieren.'
      author: 'Sandra Helfenstein'
      role: 'Co-Leiterin Kommunikation'
      logo: '/media/graphics/logos/sbv.svg'
    - quote: 'Dank der persönlichen Beratung haben wir für unser Crowdfunding Projekt schnell die passende Lösung gefunden. Emotionale Bilder die bewegen haben zum Erfolg für die Realisierung beigetragen. Herzlichen Dank.'
      author: 'Lukas Bregenzer'
      role: 'Inhaber'
      logo: '/media/graphics/logos/swiss-local-travel.svg'
    - quote: 'reiheacht hat uns vom Storyboard über das Drehen bis hin zur fertigen Produktion sehr kompetent unterstützt. Dank seiner freundlichen, humorvollen und professionellen Art und Weise war die Zusammenarbeit mit Marc jederzeit sehr angenehm.'
      author: 'Natasa Kovacevic'
      role: 'Leiterin Marketing'
      logo: '/media/graphics/logos/it-point.svg'
    - quote: 'Herzlichen Dank an das reiheacht Team, welches uns von A - Z professionell unterstützt und beraten hat. Wir freuen uns auf eine weitere Zusammenarbeit.'
      author: 'Thomas Rüttimann'
      role: 'Materialchef'
      logo: '/media/graphics/logos/gcz.svg'
    - quote: 'Unkomplizierte und sehr speditive Zusammenarbeit. Kann ich nur weiterempfehlen. Falls ich wieder ein Video brauche, komme ich definitiv wieder auf euch zu.'
      author: 'Jessica Glaus'
      role: 'Inhaberin'
      logo: '/media/graphics/logos/hairbreak.svg'
    - quote: 'reiheacht hat die Creatives für unsere Adventskampagne 2021 schnell und unkompliziert gestaltet. Unsere Illustrationen aus früheren Projekten haben sie geschickt weiterentwickelt, so dass wir viele Variationen umsetzen konnten. '
      author: 'Dorothea Portmann'
      role: 'Fachspezialistin Kommunikation'
      logo: '/media/graphics/logos/hotellerie-suisse.svg'
    - quote: 'Marc hat uns von der Konzeption bis zum fertigen Werbevideo professionell und kreativ unterstützt. Wir sind begeistert vom Ergebnis und würden reiheacht wieder wählen. '
      author: 'Daniel Gares'
      role: 'Leiter Verkauf & Marketing'
      logo: '/media/graphics/logos/altuna.svg'
