dateModified: 1649077024
email:
  fromEmail: tools@haaswebsolutions.io
  fromName: Reiheacht
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    1b49fd40-d90f-4f3d-bf96-7cb4f2bedffd: Text # Text
    1e2a8ec8-bbf2-4ebe-95a4-91b4a49f13b1: Project # Project
    1e4e377a-85e5-4dc3-ac61-20057973505f: 'Rich Text' # Rich Text
    4c614a57-4511-4b31-8cc7-01f589ea3987: Projects # Projects
    6dbcd30b-b235-4b2a-b257-41cb7044dcf3: Client # Client
    36bccdfa-ddb0-4bce-a12b-1e1e71d96519: 'Project Infobox Logo' # Project Infobox Logo
    41c3ceb6-6f88-48e4-a579-1b127b734427: 'Project Detail Description' # Project Detail Description
    045c86b9-5f90-4c25-ada4-964b3afc3d96: 'Project Tile Heading' # Project Tile Heading
    557d13d8-bdf7-470b-8df9-c5b75b762d47: Reiheacht # Reiheacht
    639cd615-fa76-49be-a252-a4af968023e9: Reiheacht # Reiheacht
    5030cc07-b585-4851-bce9-2813cf3af1f1: 'Project Infobox Subheading' # Project Infobox Subheading
    21408961-3404-4135-a29e-4aa2e9d688e3: 'Project Tile Subheading' # Project Tile Subheading
    a3b55356-2035-4f54-8225-2026513ec0ef: Color # Color
    a58ea7dc-6a9e-4b2d-9ea8-514de7490bc9: Target # Target
    ae766595-dac6-4467-b496-54f74ab25a62: 'Project Detail Heading' # Project Detail Heading
    af508af9-d355-4b8c-ba92-b0db4ad26825: Intro # Intro
    b0df425f-c398-425c-b8c9-8f1245a080cc: 'Project Infobox Heading' # Project Infobox Heading
    b2314008-e575-459b-864c-b45e396e57c1: 'Project Tile Color' # Project Tile Color
    bcb328af-f26b-4687-80c2-af0d1ae93a5b: Logos # Logos
    c656f1bc-b3e7-4e6b-bea8-da1f3254e94e: Project # Project
    c723ce3a-0eb9-41dd-84a1-e97ed43fce23: Common # Common
    edda66b7-c42a-4454-9755-9c28dda0d07a: Heading # Heading
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
system:
  edition: solo
  live: true
  name: Reiheacht
  schemaVersion: 3.7.33
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
